import {
  ANNUAL_KWH_PER_SQUARE_METER,
  CO2_KG_PER_KWH,
  ELECTRICITY_RATE_KRW as RE100_ELECTRICITY_RATE_KRW,
  INSTALLABLE_ROOF_RATIO,
  INSTALL_COST_KRW_PER_M2,
} from "@/lib/solar-calculations";

export const YU_CENTER = { lat: 35.832, lng: 128.756 };
export const YU_DEFAULT_ZOOM = 16.3;
export const YU_DEFAULT_PITCH = 50;
export const YU_DEFAULT_BEARING = -17;
export const CO2_FACTOR = CO2_KG_PER_KWH;
export const ELECTRICITY_RATE_KRW = RE100_ELECTRICITY_RATE_KRW;
export const SOLAR_PANEL_KWH_PER_M2_YEAR = ANNUAL_KWH_PER_SQUARE_METER;
export const ROOF_COVERAGE_RATIO = INSTALLABLE_ROOF_RATIO;
export const SOLAR_INSTALL_COST_KRW_PER_M2 = INSTALL_COST_KRW_PER_M2;
